import { useNavigate } from "react-router-dom";
import "./Portal.css";

function Portal() {
    const navigate = useNavigate();

    return (
        <div className="portal-page">

            {/* TOP NAV */}
            <header className="portal-nav">

                <button
                    className="portal-brand"
                    onClick={() => navigate("/")}
                >
                    <img
                        src="/branding/agrogard-logo.png"
                        alt="AgroGuard-AI"
                    />

                    <div>
                        <strong>AgroGuard<span>-AI</span></strong>
                        <small>FARMER INTELLIGENCE PORTAL</small>
                    </div>
                </button>

                <button
                    className="portal-back"
                    onClick={() => navigate("/")}
                >
                    ← Back to website
                </button>

            </header>


            {/* MAIN */}
            <main className="portal-main">

                <section className="portal-hero">

                    <div className="portal-copy">

                        <div className="portal-eyebrow">
                            AGROGUARD-AI · FARMER PORTAL
                        </div>

                        <h1>
                            Your fields.
                            <br />
                            <em>Your intelligence.</em>
                        </h1>

                        <p>
                            Access your agricultural dashboard, monitor
                            your fields, review AI-powered crop detection
                            results and receive actionable farm intelligence.
                        </p>

                        <div className="portal-actions">

                            <button
                                className="portal-primary"
                                onClick={() => navigate("/login")}
                            >
                                Login
                                <span>→</span>
                            </button>

                            <button
                                className="portal-secondary"
                                onClick={() => navigate("/signup")}
                            >
                                Create Farmer Account
                            </button>

                        </div>

                    </div>


                    {/* VISUAL */}
                    <div className="portal-visual">

                        <div className="portal-orbit orbit-1" />
                        <div className="portal-orbit orbit-2" />
                        <div className="portal-orbit orbit-3" />

                        <div className="portal-center">

                            <img
                                src="/branding/agrogard-logo.png"
                                alt=""
                            />

                            <strong>AG</strong>

                            <span>AI FIELD INTELLIGENCE</span>

                        </div>


                        <div className="portal-data data-1">
                            <strong>FIELD HEALTH</strong>
                            <span>MONITORING ACTIVE</span>
                        </div>

                        <div className="portal-data data-2">
                            <strong>AI ANALYSIS</strong>
                            <span>READY</span>
                        </div>

                        <div className="portal-data data-3">
                            <strong>ADVISORY</strong>
                            <span>PERSONALISED</span>
                        </div>

                    </div>

                </section>


                {/* FEATURES */}
                <section className="portal-features">

                    <div className="portal-feature">
                        <span>01</span>
                        <strong>Field Monitoring</strong>
                        <p>
                            Track crop conditions and field observations
                            through the AgroGuard intelligence workflow.
                        </p>
                    </div>

                    <div className="portal-feature">
                        <span>02</span>
                        <strong>AI Detection</strong>
                        <p>
                            Review crop disease, pest and severity
                            information generated by the system.
                        </p>
                    </div>

                    <div className="portal-feature">
                        <span>03</span>
                        <strong>Smart Advisory</strong>
                        <p>
                            Receive recommendations designed around
                            your crop and field information.
                        </p>
                    </div>

                </section>

            </main>

        </div>
    );
}

export default Portal;